apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dev
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: container-dev
          image: rayanabonfantidocker/spring-boot-docker-ec2:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
  selector:
    matchLabels:
      app: nginx-pod
---
apiVersion: v1
kind: Service
metadata:
  name: service-dev
spec:
  selector:
    app: nginx-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-dev
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
