apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dev
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: container-dev
          image: rayanabonfantidocker/spring-boot-docker-ec2:latest
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: nginx-pod
